
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}
    username: ${DB_ID}
    password: ${DB_PW}

  security:
    jwt:
      header: Authorization
      secret: ${JWT_KEY}
      token-validity-in-seconds: 86400

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
  config: classpath:logback-spring.xml

jasypt:
  encryptor:
    bean: jasyptEncryptor
