spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email


app:
  auth:
    tokenSecret: asdf234asdfasdfasdf123asfdzxcv
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8181/login/oauth2/code/google

jwt.secret: ${JWT_KEY}