spring:
  profiles:
    include: oauth
    active: blue

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}
    username: ${DB_ID}
    password: ${DB_PW}

  security:
    jwt:
      header: Authorization
      secret: ${JWT_KEY}
      token-validity-in-seconds: 86400

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    #    root: log
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
#  config: classpath:logback-spring.xml


---
spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: green

server:
  port: 8082

